services:
  blink-bridge:
    build: .
    image: fhem-blink-bridge:0.1.1
    container_name: blink-bridge
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/data
